事前確認 コメント編集/削除機能
daiki-mrt/tenkue-board-r012 pull request #10
Opened 2020-12-08 10:56 UTC by daiki-mrt

2020-12-08 11:06 UTC, daiki-mrt commented on app/controllers/comments_controller.rb
> +    #   params.require(:comment).permit(:comment,:post_id).merge(user_id: current_user.id)
- `<%= f.hidden_field :post_id, value: params[:id] %>`の記述と合わさって、`update`アクション時に 編集したいcommentの`post_id`が新たに採番される(→外部キーpost_idが無いというエラー)ようになりました。

**対応**
- `params[:comment][:post_id]`ではなく、`params[:post_id]`を`merge`するようにしたいと思います。

2020-12-08 11:06 UTC, daiki-mrt commented on app/views/posts/show.html.erb
> +                <%# <%= f.hidden_field :post_id, value: params[:id] %>
- 保留でいったんコメントアウトしてます。

2020-12-08 11:47 UTC, Kamiyama-k1911 commented on app/controllers/comments_controller.rb
> +    #   params.require(:comment).permit(:comment,:post_id).merge(user_id: current_user.id)
<%= f.hidden_field :post_id, value: params[:id] %> → <%= f.hidden_field :post_id, value: **@post.id** %>に変更で治ったりしないですかね？チラッと調べてみたら出てきたんですけど！

もしそれで治らないなら、後はお任せします！

2020-12-08 11:56 UTC, daiki-mrt commented on app/controllers/comments_controller.rb
> +    #   params.require(:comment).permit(:comment,:post_id).merge(user_id: current_user.id)
全然説明が足りなかったですね…申し訳ないです！
頂いたコメントも合わせて明日もう少し試してみます！

2020-12-08 14:46 UTC, daiki-mrt commented on app/controllers/comments_controller.rb
> +    #   params.require(:comment).permit(:comment,:post_id).merge(user_id: current_user.id)
ありがとうございます！
変化の少ない、`f.hidden_field :post_id, value: params[:@post.id]` でビューを修正する方でいきますね！
今まではパラメータから拾って`merge`するやり方を取ってたんですけど、こういうやり方も出来ますね！発見でした！

2020-12-08 15:01 UTC, Kamiyama-k1911 commented on app/controllers/comments_controller.rb
> +    #   params.require(:comment).permit(:comment,:post_id).merge(user_id: current_user.id)
了解しました！

2020-12-09 04:58 UTC, daiki-mrt commented
@Kamiyama-k1911 
`comments#create` と `comments#update` の `else~` について
共通してるので `respond_alert` みたいなメソッドでまとめた方がいいのかな？
と思ったのですが、どう思います？

2020-12-09 05:48 UTC, Kamiyama-k1911 commented
> comments#create と comments#update のelse~(フラッシュメッセージを出す部分) について
共通してるので respond_alert みたいなメソッドでまとめた方がいいのかな？
と思ったのですが、どう思います？

コントローラーがスッキリするので、良いと思います！
LGTMなので、メソッドでまとめてしまったら壮さんにレビューお願いしてしまって大丈夫です！

2020-12-09 06:10 UTC, sew-sou19 requested changes
おー！さすがですね！
一点だけご確認お願いします！

2020-12-09 06:10 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +  before_action :access_limit, only: [:edit, :update, :destroy]
`access_limit`はpostコントローラーでも書かれているので、リファクタできそうです！
例えば、この後作るであろうlikeコントローラーでも同じ記述をすることになりそうなので、このメソッドはapplicationコントローラーにまとめてあげるとよさそうです。

逆にログインしなくても使用できるアクション(post/showなど)は、`skip_before_action`で逃げられます。

2020-12-10 01:22 UTC, daiki-mrt commented on app/controllers/comments_controller.rb
> +  before_action :access_limit, only: [:edit, :update, :destroy]
下記のように修正してみました。
壮さんのイメージ通りかが不安なのですが、一度ご確認お願いします！

**やったこと**
- `access_limit`をapplicationコントローラーに作成
- post, commentコントローラーで`access_limit`を呼び出す（onlyオプションでアクションを指定）

**レビュー時からの変化点**
- comment編集制限時に、投稿詳細ではなくrootパスへリダイレクトされるようになった

**挙動確認**
- 投稿者以外のpostの編集
[![Image from Gyazo](https://i.gyazo.com/9b6215696d1c397b0b571218efd6fd07.gif)](https://gyazo.com/9b6215696d1c397b0b571218efd6fd07)
- 投稿者以外のcommentの編集
[![Image from Gyazo](https://i.gyazo.com/68c4ff330bd56225e6dfa79ad1b9fb90.gif)](https://gyazo.com/68c4ff330bd56225e6dfa79ad1b9fb90)

2020-12-10 01:30 UTC, sew-sou19 approved these changes
めちゃくちゃ高度な実装にしてくださいましたね😂
これはこれで素晴らしいです！LGTMですー！

2020-12-10 02:18 UTC, merged