いいね機能
daiki-mrt/tenkue-board-r012 pull request #11
Opened 2020-12-10 11:08 UTC by Kamiyama-k1911

### 前提
- Likeモデルを作成
- likes_controllerを作成
- routes.rbに`resource :likes, only: [:create, :destroy]`を追加。

### 要件
- 1ユーザーあたり、1投稿に対して1回のみいいねが押せるようになっている
   - likes_controller.rbにcreateアクションを作成
   - **exists?メソッド**を使い、いいねが押されている時はdestroyアクションのリンクを表示し、押されていない時はcreateアクションのリンクを表示。
  
- いいねが押されている状態でもう一度いいねを押すと、いいねが取り消される
  - likes_controller.rbにdestroyアクションを作成
  - **exists?メソッド**を使い、いいねが押されている時はdestroyアクションのリンクを表示し、押されていない時はcreateアクションのリンクを表示。
- 未ログイン時にはいいねボタンを押せないようになっている
  - likes_controller.rbに`before_action :authenticate_user!`を記述
- いいねをカウントできている

  - show.html.erbとindex.html.erbに**lengthメソッド**を用いて記述。

### その他
- 連打対策
  - likes_controller.rbに記述。createアクションに既にいいねが押されている場合、destroyアクションにはmodelが空(既にいいねが消されている)の場合、直前のページに戻る処理を記述。
### 画像・動画
#### いいねを押せる・取り消せる。また、カウント数が変わる。
![転クエ掲示板-お気に入り](https://user-images.githubusercontent.com/56924003/101762460-d268ae00-3b20-11eb-8bd1-7651c2766dd4.gif)

#### 未ログイン時
![転クエ掲示板-お気に入り（未ログイン時）](https://user-images.githubusercontent.com/56924003/101762529-e3b1ba80-3b20-11eb-8230-0430cabd6afb.gif)

#### ボタン連打時（動画からは全くわからないと思いますが、一応載せておきます....）
![転クエ掲示板-お気に入り連打](https://user-images.githubusercontent.com/56924003/101764282-3c825280-3b23-11eb-8ac8-c15b217c56cd.gif)

2020-12-10 12:06 UTC, daiki-mrt commented
お疲れさまです！LGTMです！

2020-12-10 13:40 UTC, sew-sou19 requested changes
レビュー完了しました！
ご確認お願いします🙏

2020-12-10 13:40 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +  before_action :authenticate_user!, only: [:edit]
ここの記述は不要かと思います！

2020-12-10 13:40 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  before_action :authenticate_user!
ここも`before_action -> { access_limit(@like) }, only: [:destroy]`があるので不要ですね！

2020-12-10 13:40 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    #お気に入り作成ボタンを連打した時の対策
おー！ここまで考えて実装できるのはすばらしいですね！！

ここはあえて一歩踏み込んでレビューしますが、この処理(メソッド)はモデルに書くべきです！
Fat Controllerを避けるのが目的ではありますが、Rubyの考え方的にも、クラスに紐づくメソッドは極力モデルに書くのがよしとされてます。

ただ、もし実装が難しければこのままでも大丈夫です！

2020-12-10 13:40 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  before_action :set_like, only: [:destroy]
ここのメソッドの共通化は不要ですね！
将来、何か別のことに使う予見ができるなら別ですが、今回のケースは不要かと思います。

2020-12-10 13:40 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
ここ、`id: params[:id])`でfindしてない理由って何かありますでしょうか？
もしなければ少し冗長かなと思うので、修正しましょう！

2020-12-10 13:40 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  def like_param
ここも`set_like`と同様で、別の処理に使う可能性が高ければ共通化するべきですが、今回のケースではそうではないかと思うので、不要かと！

2020-12-10 13:40 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  def access_limit(model)
これは`application_controller.rb`で定義してるので不要かと思います！
もりもりさんのPRを見てみましょう！

2020-12-10 13:40 UTC, sew-sou19 commented on config/routes.rb
> +    resource :likes, only: [:create, :destroy]
あーなるほど、likeのルーティングでresourceを使用されたんですね。
ここも、あえてresourceを使用する目的があればOKです。もし明確な理由がないなら、resourcesとしておくほうが無難な気もします

https://qiita.com/Atsushi_/items/bb22ce67d14ba1abafc5

2020-12-10 13:52 UTC, Kamiyama-k1911 commented on app/controllers/comments_controller.rb
> +  before_action :authenticate_user!, only: [:edit]
これを記述しないと、ブラウザでコメント編集のURLを直打ちした時にエラーが出てしまいますが良いのでしょうか？理由としては未ログイン時には`access_limit`メソッドでcurrent_userがnilになってしまうからだと思います！

2020-12-10 14:03 UTC, Kamiyama-k1911 commented on app/controllers/likes_controller.rb
> +  before_action :authenticate_user!
これも書かないとエラーが出てしまいます！理由はcreateアクションで`current_user.likes.build(like_param)`でというコードを書いているので、current_userがnilになってしまうからだと思います。
確かにdestroyは無くても良いと思いますので、変えるとしたら`before_action :authenticate_user!, only: [:create]`という記述になるんじゃないかと自分は思ったのですが何か認識違いなどありますでしょうか？

2020-12-10 14:03 UTC, Kamiyama-k1911 commented on app/controllers/likes_controller.rb
> +    #お気に入り作成ボタンを連打した時の対策
クラスメソッドの理解が怪しいのでこの機会に修正したいと思います！
ありがとうございます！

2020-12-10 14:07 UTC, Kamiyama-k1911 commented on app/controllers/likes_controller.rb
> +  before_action :set_like, only: [:destroy]
このset_likeをメソッド化している理由は、`access_limit`メソッドでインスタンス変数を使用しているからです！`access_limit`メソッドより先にインスタンス変数を取得しておかないとエラーが起きてしまうためset_likeを作りました！自分としてはそれ以外に良い方法が思い浮かばなかったので、違和感はありつつもこういう実装になりました。何かアドバイスいただければ嬉しいです！

2020-12-10 14:11 UTC, Kamiyama-k1911 commented on config/routes.rb
> +    resource :likes, only: [:create, :destroy]
resourcesだとlikeのidの取得が難しいためresourceを使いました！
別のご指摘でもありましたように、確かに`@like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])`だと長いと思うので、resourcesを使った方が良かったでしょうか？

2020-12-10 14:12 UTC, Kamiyama-k1911 commented on app/controllers/likes_controller.rb
> +  def like_param
おっしゃる通りです！修正します！ありがとうございます！

2020-12-10 14:18 UTC, Kamiyama-k1911 commented on app/controllers/likes_controller.rb
> +  def access_limit(model)
これは`application.controller.rb`のaccess_limitのメソッドをオーバーライドしています！理由としては、いいね削除ボタンを連続で押した時にエラーしないようにするためです！destroyアクション内で上手く対処できれば良かったのですが、上手い実装方法が見つからず、`access_limit`メソッドに処理を追加する形になりました！

2020-12-10 14:52 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +  before_action :authenticate_user!, only: [:edit]
なるほど！そしたら`access_limit`側の挙動を変えてあげたほうがいいですね！

2020-12-10 14:52 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  before_action :authenticate_user!
同上です

2020-12-10 14:56 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  before_action :authenticate_user!
いろいろと不整合が出てますねー！
いずれにしても`before_action :authenticate_user!`をあちこちのコントローラーで記述するのはあまりきれいではないです。

ログインしないと動作しないコントローラーを作成するたびに、毎回書かなくてはならないので。
`before_action :authenticate_user!`をapplicationコントローラーで記述して、ログインが不要なアクション（`posts/index`など）は、`skip_before_action`を書いてあげたほうがいいかな、という気がします！

※ここも`access_limit`の処理を変更する前提で書いてます

2020-12-10 14:57 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  before_action :set_like, only: [:destroy]
おー！なるほどです。
`access_limit `の処理を変えてあげることも考えてみるといいかもですね！

ぜひもりもりさんと相談してみてください！
その結果、この記述でいくとなっても全然大丈夫です。

2020-12-10 14:58 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  def access_limit(model)
あ、オーバーライドしてたんですね！了解です。
もし`access_limit`の処理を変更するなら、ここも合わせて見返すといいかもです！

2020-12-10 15:07 UTC, sew-sou19 commented on config/routes.rb
> +    resource :likes, only: [:create, :destroy]
そうですね！
`resource`はその名の通り一つbリソースを示しているので、ネストするクラスの場合は、親:子=1:1の時の方に使ったほうがいいかと思います。

今回は、user(or post):like = 1:nなので、idがあったほうがいい気もします。
（まあもっと厳密に言うと、user_id × post_id : like = 1:1なので、的外れでもないです）

結論、どちらでもいいです。
ただlikeのidは取得しようと思えばできるので、その方法を考えてみて、どちらがいいかご自身で考えていただくのがいいかと思います！

2020-12-10 15:09 UTC, Kamiyama-k1911 commented on app/controllers/comments_controller.rb
> +  before_action :authenticate_user!, only: [:edit]
確かにそうですね！ご指摘いただいている点に`access_limit`が絡んでいる場所が多いので、考えたいと思います！

2020-12-10 15:10 UTC, Kamiyama-k1911 commented on app/controllers/likes_controller.rb
> +  before_action :authenticate_user!
なるほど！`before_action :authenticate_user!`の使い方、頂いたアドバイスを元に再度修正してみます！

2020-12-10 15:11 UTC, Kamiyama-k1911 commented on app/controllers/likes_controller.rb
> +  def access_limit(model)
そうですね！ここと合わせて考えてみます！

2020-12-10 15:15 UTC, Kamiyama-k1911 commented on config/routes.rb
> +    resource :likes, only: [:create, :destroy]
ありがとうございます！考えてみます！

2020-12-11 08:45 UTC, Kamiyama-k1911 commented
新しくset_modelメソッドを作成しました！理由としては、1箇所だけしか使っていないのに、`set_like`メソッドを定義しなければならないためです。どうすればいいかと考えた時に`set_post`、`set_comment`、`set_like`を1つのメソッドでまとめて定義できればいいのではないか？と思いつき、`controller_name`というコントローラー名を取得してくれるメソッドを使い条件分岐を作成しました！

2020-12-11 14:55 UTC, sew-sou19 approved these changes
おー！めちゃくちゃ考えてくださいましたね！
LGTMです！！いやー綺麗になった！

2020-12-11 15:38 UTC, Kamiyama-k1911 commented
ありがとうございます！！！

2020-12-11 15:43 UTC, merged