掲示板一覧表示機能を実装
daiki-mrt/tenkue-board-r012 pull request #4
Opened 2020-11-30 09:28 UTC by Kamiyama-k1911

### 要件
- #### 掲示板を一覧で表示できる
  - `posts_controller.rb`のindexアクションの中身を記述し、`index.html.erb`に**each文**を記述
  - 投稿が0件だったときの分岐を`index.html.erb`に記述
- #### 投稿者だけにスレッドの編集・削除リンクが表示される
  - `posts_controller`の`index.html.erb`に**if文を**記述
- #### 未ログイン状態でも閲覧できる
  - `posts_controller`の`index.html.erb`に**if文を**記述

- #### N+1問題を発生させていない
  - `posts_controller.rb`のindexアクションに`preload(:user)`を記述

### その他
- #### 日本時間に設定
  - `config/application.rb`に`time_zone`の設定を記述

- #### 時間のフォーマットを変更
  - `posts_controller`の`index.html.erb`に記述

### 画像
#### 投稿0件の時
<img width="1440" alt="投稿0件" src="https://user-images.githubusercontent.com/56924003/100591585-53fa5800-3339-11eb-95ef-c97d1becf823.png">

#### ログインしていなくても閲覧できる
<img width="1440" alt="スクリーンショット 2020-11-30 17 15 22" src="https://user-images.githubusercontent.com/56924003/100591708-7a1ff800-3339-11eb-9859-f1e69adf3689.png">

#### 投稿者だけが編集・削除できる
<img width="1440" alt="スクリーンショット 2020-11-30 17 15 48" src="https://user-images.githubusercontent.com/56924003/100591794-9885f380-3339-11eb-816c-d4b0212c92b0.png">

2020-11-30 10:03 UTC, daiki-mrt reviewed
自分の勉強不足だったら、非常に申し訳ないですが一つだけ質問したいです！
調べてみたのですが、違いが理解できず…
https://qiita.com/ryosuketter/items/097556841ec8e1b2940f
https://qiita.com/k0kubun/items/80c5a5494f53bb88dc58

2020-11-30 10:17 UTC, Kamiyama-k1911 commented on app/controllers/posts_controller.rb
> +    @posts = Post.preload(:user).all
僕もそこらへん曖昧だったのですが、`preload(:users)`と`preload(:user)`を両方試してみて分かりました！
結論は`preload(:users)`だと誤りになりました！
なぜ`:users`だと誤りになるのかは、**PostモデルとUserモデルの関係性**が違うからだと思います。
PostモデルはUserモデルに対して`belongs_to`になるので、`users`ではなく`user`なんだと思います！

2020-11-30 10:28 UTC, daiki-mrt commented on app/controllers/posts_controller.rb
> +    @posts = Post.preload(:user).all
なるほど… 😲

2020-11-30 10:29 UTC, daiki-mrt commented
コメントありがとうございました！
LGTMです！

2020-11-30 10:43 UTC, Kamiyama-k1911 commented on app/controllers/posts_controller.rb
> +    @posts = Post.preload(:user).all
もしかしたら間違っているかもしれませんので、あくまで参考程度にお願いします！笑

2020-12-02 04:44 UTC, sew-sou19 commented
> 自分の勉強不足だったら、非常に申し訳ないですが一つだけ質問したいです！
> 調べてみたのですが、違いが理解できず…

`preload`と`eager_load`の違いは、一言で言えば**「取得したデータの絞り込みができるか否か」**です。
- preload → 以下のようにレコードの絞り込みができない（テーブル結合してないため）
`@myPosts = Posts.preload(:user).where(user_id: current_user)`

- eager_load → できる
`@myPosts = Posts.eager_load(:user).where(user_id: current_user)`

`inclueds`はその辺を特に考えずに、場合に応じて処理を変えてくれるイメージです。

2020-12-02 04:51 UTC, sew-sou19 requested changes
1点だけご確認お願いしますー！

2020-12-02 04:51 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @posts = Post.preload(:user).all
> なぜ:usersだと誤りになるのかは、PostモデルとUserモデルの関係性が違うからだと思います。
> PostモデルはUserモデルに対してbelongs_toになるので、usersではなくuserなんだと思います！

これはその通りですー！アソシエーションの関係からですね。

ただ、ここは`preload`より`eager_load`がいいかと思います！
preloadで取得した場合、postクラスからuserクラスの値を参照できなくなってしまうので。。。

もしこの辺の理解が怪しいようであれば`includes`でもひとまず問題はないです！

それぞれの[主な違いはこれ](https://qiita.com/ryosuketter/items/097556841ec8e1b2940f#%E4%B8%BB%E3%81%AA%E9%81%95%E3%81%84)です。

2020-12-02 05:06 UTC, Kamiyama-k1911 commented
レビューありがとうございます！
ご指摘いただいた点を`eager_load`に修正したいと思います！
`preload`と`eager_load`の違いについてまだ完全に理解できていませんが、**アソシエーションによって使い分けるのが大事**で、１対Nのアソシエーションの場合は`eager_load`を使った方が良いという解釈でよろしいでしょうか？

2020-12-02 05:52 UTC, sew-sou19 commented
> アソシエーションによって使い分けるのが大事で、１対Nのアソシエーションの場合はeager_loadを使った方が良いという解釈でよろしいでしょうか？
厳密には違いますね、、、アソシエーションによって使い分けるものではないです。
テーブル同士を結合（してデータを参照）する場合か否か、ですね

自分なりに調べてみてくださいー！

2020-12-02 05:53 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-02 05:56 UTC, Kamiyama-k1911 commented
>厳密には違いますね、、、アソシエーションによって使い分けるものではないです。
テーブル同士を結合（してデータを参照）する場合か否か、ですね
自分なりに調べてみてくださいー！

そうなんですね！
`テーブル同士を結合（してデータを参照）する場合か否か`
ここを意識して調べていきたいと思います！
ありがとうございます！

2020-12-02 05:59 UTC, merged