コメント投稿機能
daiki-mrt/tenkue-board-r012 pull request #9
Opened 2020-12-07 06:54 UTC by Kamiyama-k1911

### 要件
- 投稿詳細ページでコメントができる
  - comments_controller.rbにcreateアクションを作成
  - routes.rbに`resources :comments, only: [:create]`を記述
  - posts_controllerのshow.html.erbにコメント投稿フォームを作成。
  - posts_controller.rbのshowアクションにインスタンス変数を追加。
- コメントは140文字以内であること
  - comment.rbに `validates :comment, length: { maximum: 140 }`を記述。

- 投稿したコメントは、投稿詳細ページに一覧で表示される
  - posts_controllerのshow.html.erbに**each文**を記述。
  - posts_controller.rbのshowアクションにインスタンス変数を追加。

- コメントの投稿内容が必須になっている（ブランクのまま投稿できないようになっている）
  - comment.rbに`validates :comment, presence: true`を記述。
- バリデーションに反した際に、エラーメッセージが表示される
  - パーシャルの_notifications.html.erbに`flash[:alert]`の記述を追加。
  - comments_controller.rbにcreateアクションに`flash[:alert] = "バリデーションに反したエラー"`という形で記述。
- 未ログイン時にはコメント投稿フォームが表示されないようになっている
  - コメント投稿フォームに対して**if文**を記述。
- コメントの数がカウントされている
  - posts_controllerのindex.html.erbとshow.html.erbで**lengthメソッド**を使い記述。
- N+1問題を発生させていない
  - posts_controller.rbのshowアクションの`@comments`に対して**eager_load**メソッドを使用。
### その他
- コメントの日本語化

  - config/locales/models/ja.ymlに記述。

### 画像・動画
#### 投稿詳細ページでコメントできる
![転クエ掲示板-コメント投稿](https://user-images.githubusercontent.com/56924003/101316492-e8b40700-389f-11eb-8b1d-fd48697d447c.gif)

#### バリデーションとエラーメッセージ
![転クエ掲示板-コメントバリデーション](https://user-images.githubusercontent.com/56924003/101316546-06816c00-38a0-11eb-8926-4c56ed99a451.gif)

#### コメント数 投稿一覧
<img width="1433" alt="転クエ掲示板-投稿一覧コメント数" src="https://user-images.githubusercontent.com/56924003/101316862-b35be900-38a0-11eb-842b-1b62f47f8a43.png">

#### コメント数 投稿詳細
<img width="1438" alt="転クエ掲示板-投稿詳細コメント数" src="https://user-images.githubusercontent.com/56924003/101316891-be167e00-38a0-11eb-9192-9ef805f6c156.png">

2020-12-07 08:12 UTC, daiki-mrt reviewed
機能は実現できているので全体としてはLGTMなのですが、コメントのところのご意見を聞いてみたいです！

2020-12-07 08:12 UTC, daiki-mrt commented on app/controllers/comments_controller.rb
> +    if not @comment.save
どれがベストか、今回の実装で可能なのか自信がないのですが、エラーメッセージを[この記事](https://railsguides.jp/active_record_validations.html#%E3%83%90%E3%83%AA%E3%83%87%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%A8%E3%83%A9%E3%83%BC%E3%82%92%E3%83%93%E3%83%A5%E3%83%BC%E3%81%A7%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B) のように実装して、 `if @comment.save else render ~` の方が僕だったら分かりやすいかなあと思いました！

2020-12-07 08:30 UTC, Kamiyama-k1911 commented on app/controllers/posts_controller.rb
> +    @comments = Comment.eager_load(:user).where(post_id: params[:id])
これに関してはwhereで絞らないと、全てのコメントが投稿詳細ページに表示されてしまいます！
投稿詳細ページには、1つの投稿に対するコメントだけを表示したいのでwhereで絞っております！

2020-12-07 08:38 UTC, Kamiyama-k1911 commented on app/controllers/comments_controller.rb
> +    if not @comment.save
app/views/shared/_error_messagesの書き方の方が良いって事ですよね？
コメント投稿フォームの中でエラーメッセージを表示をさせるなら、それで良いと思うのですが、コメント投稿のバリデーションはヘッダーの下でflash[:alert]として表示されるものなので、今回のケースだと`<% if model.errors.any? %>`は使用しない事にしました！

2020-12-07 08:42 UTC, Kamiyama-k1911 commented on app/controllers/posts_controller.rb
> +    @comments = Comment.eager_load(:user).where(post_id: params[:id])
`@post.comments.eager_load(:user)`だけだと全ての投稿のコメントが表示されてしまいます！
投稿詳細ページには1つの投稿に対するコメントだけを表示させたいのでwhereで絞っています！

2020-12-07 08:51 UTC, daiki-mrt commented on app/controllers/comments_controller.rb
> +    if not @comment.save
了解しました！

2020-12-07 09:08 UTC, daiki-mrt commented on app/controllers/posts_controller.rb
> +    @comments = Comment.eager_load(:user).where(post_id: params[:id])
めっちゃ気になって `@comments = @post.comments.eager_load(:user)`で試してみたんですけどこういうことじゃないです？
[![Image from Gyazo](https://i.gyazo.com/490eceb7093ebd1b8631c1044ea0123b.gif)](https://gyazo.com/490eceb7093ebd1b8631c1044ea0123b)

2020-12-07 09:20 UTC, Kamiyama-k1911 commented on app/controllers/posts_controller.rb
> +    @comments = Comment.eager_load(:user).where(post_id: params[:id])
全くその通りです！
`Comment.eager_load(:user)`に見えてました！
大変申し訳ありません！

2020-12-07 09:28 UTC, daiki-mrt commented
お返事、ご対応ありがとうございます！LGTMです！

2020-12-07 12:56 UTC, sew-sou19 requested changes
レビュー完了しました！
一部ご確認をお願いします！

2020-12-07 12:56 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +    redirect_to controller: :posts, action: :show, id: params[:post_id]
`redirect_to`の引数をどれにするか、のベストプラクティスは賛否ありますが、一般的にはプレフィックスを使用したほうがいいかと思いますー！

この記述でも間違いではないのですが、読みにくいのと記述が少々冗長です。

2020-12-07 12:56 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +    end
これでも要件は満たせていますが、できればコメント失敗時(例えばコメントが141文字の時など)に、入力した内容が消えてしまうかと思います。できればそれも解消できるとなおいいです！
※必須ではないので、もし難しければこのままでも大丈夫です。

2020-12-07 12:56 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @posts = Post.eager_load(:user,:comments).all
ここでの`:comments`の`egaer_load`は不要かと思いますー！
N+1問題についてもう少しググって見ていただくといいかと思います！

2020-12-07 12:56 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @posts = Post.eager_load(:user,:comments).all
bulletというgemがあるのでもしお時間あれば試してみてください！

2020-12-07 12:56 UTC, sew-sou19 commented on app/views/shared/_notifications.html.erb
>  <%# フラッシュメッセージのテンプレートファイル %>
不要なコメントは削除しましょうー！

2020-12-07 13:49 UTC, Kamiyama-k1911 commented on app/views/shared/_notifications.html.erb
>  <%# フラッシュメッセージのテンプレートファイル %>
すいません！見逃しておりました！

2020-12-07 13:50 UTC, Kamiyama-k1911 commented on app/controllers/comments_controller.rb
> +    end
修正してみます！

2020-12-07 13:51 UTC, Kamiyama-k1911 commented on app/controllers/comments_controller.rb
> +    redirect_to controller: :posts, action: :show, id: params[:post_id]
確かにそうですね！他のコントローラーのパス使う場合、コントローラ名も書かないとダメだと思っていました。ありがとうございます！

2020-12-07 13:55 UTC, Kamiyama-k1911 commented on app/controllers/posts_controller.rb
> +    @posts = Post.eager_load(:user,:comments).all
index.html.erbでコメントの数を取得していたのでいるかなと思ったのですが、あくまでカラムの数を取り出す処理をしている時に使う感じなんですかね？
まだ理解浅いので調べてみます！ありがとうございます！

2020-12-08 05:05 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @posts = Post.eager_load(:user,:comments).all
> index.html.erbでコメントの数を取得していたのでいるかなと思ったのですが、あくまでカラムの数を取り出す処理をしている時に使う感じなんですかね？

N+1問題は、テーブルからデータをSELECTするときに発生する現象ですねー！
index.html.erbだとcommentテーブルはSELECTしてないので、おそらく不要かと！_

2020-12-08 05:15 UTC, sew-sou19 reviewed
確認しました！ほぼ問題ないですー！
一点だけ、comment/createで失敗した時の挙動だけご確認お願いしますー！うまく行けばLGTMです！

2020-12-08 05:15 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +    end
これって141文字でコメント失敗した時ってどういう挙動になりますかね、、？
renderなどがないので、挙動が不安になりまして🙏

2020-12-08 05:24 UTC, Kamiyama-k1911 commented
>これって141文字でコメント失敗した時ってどういう挙動になりますかね、、？

こんな感じですね！きちんと動いているとは思います！
![転クエ掲示板-コメントバリデーション2](https://user-images.githubusercontent.com/56924003/101443484-da79ef80-3960-11eb-927f-1e3fa7a782e3.gif)

2020-12-08 05:34 UTC, Kamiyama-k1911 commented on app/controllers/posts_controller.rb
> +    @posts = Post.eager_load(:user,:comments).all
なるほど！勉強になります！ありがとうございます！

2020-12-08 05:42 UTC, sew-sou19 commented
OKです！
jsで挙動制限してるってことですねー！LGTMです！

2020-12-08 05:43 UTC, sew-sou19 approved these changes

2020-12-08 05:46 UTC, Kamiyama-k1911 commented
> jsで挙動制限してるってことですねー！

僕もそういう事だと認識しております！

2020-12-08 05:46 UTC, merged